---
- name: i want to install apache2
  hosts: all
  become: yes
  tasks:
   - name: i want apCHE2
     apt:
      name: apache2
      update_cache: yes
      state: present
   - name: start apache service
     systemd:
      name: apache2
      state: started
~                                                                                                                                                   ~  